"""Typed stubs for the phase_flow extension module."""

import numpy as np
from numpy.typing import NDArray

REGIME_NAMES: list[str]

class Sim:
    @staticmethod
    def from_json(scenario_json: str) -> Sim: ...
    def run(self, t: float) -> None: ...
    def step(self) -> float: ...
    def set_bc(self, wg: float, wl: float, p_out: float, choke: float) -> None: ...
    def set_muscl(self, on: bool) -> None: ...
    def refresh_regime(self) -> None: ...
    def mass_totals(self) -> tuple[float, float]: ...
    def save_state(self) -> NDArray[np.float64]: ...
    def load_state(self, data: NDArray[np.float64], time: float, steps: int) -> None: ...
    @property
    def steps(self) -> int: ...
    @property
    def time(self) -> float: ...
    @property
    def dt_last(self) -> float: ...
    @property
    def n_cells(self) -> int: ...
    @property
    def alpha_g(self) -> NDArray[np.float64]: ...
    @property
    def p(self) -> NDArray[np.float64]: ...
    @property
    def vg(self) -> NDArray[np.float64]: ...
    @property
    def vl(self) -> NDArray[np.float64]: ...
    @property
    def am(self) -> NDArray[np.float64]: ...
    @property
    def x(self) -> NDArray[np.float64]: ...
    @property
    def elevation(self) -> NDArray[np.float64]: ...
    @property
    def dx(self) -> NDArray[np.float64]: ...
    @property
    def regime(self) -> NDArray[np.uint8]: ...

def classify_point(
    alpha: float,
    jg: float,
    jl: float,
    d: float,
    sin_th: float = 0.0,
    cos_th: float = 1.0,
    p: float = 1.0e5,
    g: float = 9.81,
) -> int: ...
def wood_speed(alpha: float, p: float) -> float: ...
